### ISSUE TITLE
[website]Official website www.alternatekicadlibrary.com is down

### ISSUE THREAD

**Issue by TurnOffNOD** [DawidCislo/Alternate-KiCad-Library#6]
Hi, website www.alternatekicadlibrary.com is down, it shows "Website Expired":

![Screenshot_20231009_183238](https://github.com/DawidCislo/Alternate-KiCad-Library/assets/2140029/94218db3-3452-4752-8b05-02c292714950)

**Comment by DawidCislo** [comment]
Yes. I can't afford to pay website hosting fees at the moment, and because the entire project is currently on-hold I have no plans to collect donations to keep it up. I no longer have time and energy to continue making the library.
As of now I'm still paying for the domain, so I can still resume work on the project in the future without any issues.
Sorry for that.

**Comment by TurnOffNOD** [comment]
> Yes. I can't afford to pay website hosting fees at the moment, and because the entire project is currently on-hold I have no plans to collect donations to keep it up. I no longer have time and energy to continue making the library. As of now I'm still paying for the domain, so I can still resume work on the project in the future without any issues. Sorry for that.

Oh, can this website migrate to github.io, which is a free site holder provided by github? And github.io can be binded to a custom domain, so old links referenced by others will not be dead.

**Comment by DawidCislo** [comment]
Possibly, I'll look into it when I have some free time.

**Comment by DawidCislo** [comment]
New website is up and running, now hosted on Github Pages. The old Domain was succesfully transfered over and now all old links should work as well.
I had to completely rebuild the website from scratch using RocketCake since Squarespace can't export the website in html format. Expect some differences in the user experience.
You can visit the website's repository here: https://github.com/DawidCislo/DawidCislo.github.io
Page passed the DNS check and for me at least is accesible via direct link: https://alternatekicadlibrary.com/
Google and other search engine results should get updated within a couple of weeks.
If you can confirm the website is accesible for you I'll mark this one as resolved.
Sorry it took so long.
